# Info
site_name: Auticola 的 叶栈漫谈
site_url: https://Auticola.github.io/note/
site_description: 愿此行，终抵群星
site_author: Auticola


# UI
theme:
  name: material

  # 顶部栏目
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: mist       # 日间模式
      primary: white
      accent: indigo          # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-sunny  # 图标
        name: 切换至夜间模式    # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate         # 夜间模式
      primary: black
      accent: indigo        # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night  # 图标
        name: 切换至日间模式    # 鼠标悬浮提示
  language: zh # 一些提示性的文字会变成中文

  #特殊设置
  features:
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    # - navigation.instant
    - header.autohide  #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy #代码复制
    - content.action.edit
    - content.action.view
    - content.code.annotate

  icon:
    logo: material/bookmark-multiple
  
nav:
  - 首页: index.md
  - Algorithm:
    - 图论:
      - 树上问题:
        - 最近公共祖先 (LCA): Algorithm/graph/tree/LCA.md
  - Computer Science:
    - CSAPP:
      - 课程简介: CS/CSAPP/index.md
      - 笔记:
        - 一、计算机系统漫游: CS/CSAPP/note/Lec1/Lec1.md
        
plugins:
  - git-revision-date-localized:
      type: timeago #时间类型
      custom_format: "%d. %B %Y"  # 时间格式
      fallback_to_build_date: false #许回退到git 不可用时mkdocs build执行的时间
      enable_creation_date: true #是否启用创建时间
      exclude:  #排除的页面
          - index.md
      enabled: true #是否启用
      strict: true

extra_css:
  - stylesheets/extra.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  # - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css
  # - https://cdn.tonycrane.cc/utils/katex.min.css
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css

extra_javascript:
  - js/mathjax.js
  - js/katex.js
  - js/math-auto-render.js
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.17.1/flowchart.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.13.6/underscore-min.js
  - https://cdn.jsdelivr.net/npm/@mermaid-js/mermaid-mindmap@9.3.0/dist/diagram-definition.0faef4c2.min.js
  - https://cdn.jsdelivr.net/npm/markdown-it-plantuml@1.4.1/index.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/webfont/1.6.28/webfontloader.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-chtml-full.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-svg-full.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js

markdown_extensions: #详见https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/ 和 https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  # - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex: # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true